// Code generated by MockGen. DO NOT EDIT.
// Source: controller/rest/base.go

// Package mock_rest_controller is a generated GoMock package.
package mock_rest_controller

import (
	gomock "github.com/golang/mock/gomock"
)
