// Code generated by MockGen. DO NOT EDIT.
// Source: service/omdb/base.go

// Package mock_service is a generated GoMock package.
package mock_service

import (
	gomock "github.com/golang/mock/gomock"
	omdb "github.com/lokiloko/refactored-chainsaw/microservice-to-search-movies/model/omdb"
	reflect "reflect"
)

// MockOMDBService is a mock of OMDBService interface
type MockOMDBService struct {
	ctrl     *gomock.Controller
	recorder *MockOMDBServiceMockRecorder
}

// MockOMDBServiceMockRecorder is the mock recorder for MockOMDBService
type MockOMDBServiceMockRecorder struct {
	mock *MockOMDBService
}

// NewMockOMDBService creates a new mock instance
func NewMockOMDBService(ctrl *gomock.Controller) *MockOMDBService {
	mock := &MockOMDBService{ctrl: ctrl}
	mock.recorder = &MockOMDBServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockOMDBService) EXPECT() *MockOMDBServiceMockRecorder {
	return m.recorder
}

// GetPaginated mocks base method
func (m *MockOMDBService) GetPaginated(request omdb.GetPaginatedRequest) (omdb.GetPaginatedResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPaginated", request)
	ret0, _ := ret[0].(omdb.GetPaginatedResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPaginated indicates an expected call of GetPaginated
func (mr *MockOMDBServiceMockRecorder) GetPaginated(request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPaginated", reflect.TypeOf((*MockOMDBService)(nil).GetPaginated), request)
}

// GetByIMDBID mocks base method
func (m *MockOMDBService) GetByIMDBID(request omdb.GetByIDRequest) (omdb.GetByIDResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByIMDBID", request)
	ret0, _ := ret[0].(omdb.GetByIDResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByIMDBID indicates an expected call of GetByIMDBID
func (mr *MockOMDBServiceMockRecorder) GetByIMDBID(request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByIMDBID", reflect.TypeOf((*MockOMDBService)(nil).GetByIMDBID), request)
}
