// Code generated by MockGen. DO NOT EDIT.
// Source: controller/grpc/base.go

// Package mock_grpc_controller is a generated GoMock package.
package mock_grpc_controller

import (
	gomock "github.com/golang/mock/gomock"
)
